# Generated by Django 3.2.6 on 2021-08-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='NULL', max_length=255)),
                ('lname', models.CharField(default='NULL', max_length=255)),
                ('mname', models.CharField(default='NULL', max_length=255)),
                ('datepicker', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('file', models.FileField(default=0, upload_to='media/')),
            ],
        ),
    ]
