# Generated by Django 3.2.6 on 2021-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='gender',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
